In [ ]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dim of a tensor
scalar.ndim   

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
tensor= tf.constant([[[1,1],[2,2],[3,3]]])
tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 1],
        [2, 2],
        [3, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

#scalar, vector, matrix and tensors
1. A scalar is a single number
2. A vector is a number with direction
3. A matrix is a 2D array of numbers 
4. A tensor is a nD array of numbers


In [ ]:
changable_tensor= tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
print(changable_tensor)
print(unchangable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
# try to change changable_tensor
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#now try changing unchangable teensor
unchangable_tensor[0].assign(7)
#this throws an error

AttributeError: ignored

#creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))


In [ ]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967],
        [-0.29604465, -0.21134205]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
#shuffle the order:
#important when you have to shuffle the data
not_shuffled = tf.constant([[10, 7], [3,4], [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
#if you want to keep the shuffle same 
tf.random.set_seed(52) #global seed
tf.random.shuffle(not_shuffled, seed = 52) #operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#create a tensor of all ones and zeros

In [ ]:
tf.ones([10,7,3])

<tf.Tensor: shape=(10, 7, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1.,

In [ ]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#you can also trun numpy arrays into tensors
#the main differeence between numpy and tensors is that tensors can be run on GPU and TPU
import numpy as np
numpy_A =np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)

In [ ]:
#change the shape of the new tensor that we created from numpy
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

##getting info from tensors

In [ ]:
tensor_rank_4 = tf.zeros([4,4,3,2])

In [ ]:
tensor_rank_4

<tf.Tensor: shape=(4, 4, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]

##indexing tensors

In [ ]:
tensor_rank_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

how to change the rank of a tensor

In [43]:
tensor_rank_2 = tf.zeros([2,2])

In [44]:
tensor_rank_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [45]:
tensor_rank_3 = tensor_rank_2[..., tf.newaxis]

In [46]:
tensor_rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

#to expand a dimention in tensorflow

In [47]:
tf.expand_dims(tensor_rank_3, axis = 0)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]],

        [[0.],
         [0.]]]], dtype=float32)>

#Manipulating tensors in tensorflow

In [48]:
tensor = tf.constant ([[10,7], [3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [49]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [50]:
tensor /10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [51]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [52]:
#using tf.multiply 
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [54]:
tensor2 = tf.constant([[10,4], [5,5]])
tf.multiply(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  28],
       [ 15,  20]], dtype=int32)>

In [55]:
tf.add(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 11],
       [ 8,  9]], dtype=int32)>

In [56]:
tf.subtract(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  3],
       [-2, -1]], dtype=int32)>

In [57]:
tf.divide(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.  , 1.75],
       [0.6 , 0.8 ]])>

#matrix multiplication with tensorflow

In [58]:
tf.matmul(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135,  75],
       [ 50,  32]], dtype=int32)>

In [59]:
tensor3 = tf.ones([3,2])

In [63]:
tensor4 = tf.ones([2,5])

#rule for matmul 
if the number of columns for the first matrix are equal to the number of rows in
the second one then and only then you can do matrix multiplication:

In [64]:
tf.matmul(tensor3, tensor4)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]], dtype=float32)>

##matrix reshaping in tensorflow

In [66]:
a = tf.constant([[1,2],[3,3], [4,6]])
b = tf.constant([[1,2,3],[1,3,4], [6,5,3]])
a.shape, b.shape

(TensorShape([3, 2]), TensorShape([3, 3]))

In [68]:
c= tf.matmul(a,b) #can't multiply as rows and columns are different

InvalidArgumentError: ignored

#tensor reshape method

In [72]:
b = tf.reshape(b, shape=(9,1))

#turn float32 to float16 where possible for fast computation

In [74]:
B= tf.constant([1. , 2.])

In [75]:
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [76]:
#turning float32 into float16
C = tf.cast(B, dtype = tf.float16)

In [77]:
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

#Aggregating tensors

In [78]:
#get the absolute values:
E = tf.constant([-7, -10])
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [80]:
tf.abs(E) #take negative numbers and turn it into possitive numbers

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

##aggregating tensors:
1. get the minimum of a tensor
2. get the maximum of a tensor
3. get the mean of a tensor
4. sum of a tensor
5. get the standard deviation
6. get the varience 

In [81]:
E = tf.constant(np.random.randint(0,100, size = 50))

In [82]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 42, 36, 86, 66, 80, 80,  9, 69, 77, 79, 87, 24, 18, 88, 98, 98,
       13, 88, 91, 48, 70, 80, 56, 23, 43, 94, 52, 31,  3, 75, 63, 47, 65,
       91, 98, 19, 73, 83, 84, 51,  9, 64, 25, 21,  1, 72, 51, 18,  9])>

In [86]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [87]:
#find the minimum
tf.reduce_min(E) #shows the minimum value in the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [88]:
tf.reduce_max(E) #shows the maximum value in the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [89]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [90]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2826>

In [98]:
D = tf.constant(tf.cast(E, dtype = tf.float32))

In [99]:
tf.math.reduce_std(D)

<tf.Tensor: shape=(), dtype=float32, numpy=29.600163>

In [100]:
tf.math.reduce_variance(D)

<tf.Tensor: shape=(), dtype=float32, numpy=876.1696>

#finding positional max and min

In [102]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [103]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [104]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [105]:
#find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [106]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#squeezing a tensor
It removes dimentions of size 1 from the tensor

In [108]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [109]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [110]:
G_squeezed = tf.squeeze(G)

In [112]:
G_squeezed.shape

TensorShape([50])

#One hot encoding tensors

In [113]:
a_list = [0,1,2,3] 
#one hot encode
tf.one_hot(a_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [114]:
tf.one_hot(a_list, depth = 4, on_value = "waqar", off_value = "ahmed")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'waqar', b'ahmed', b'ahmed', b'ahmed'],
       [b'ahmed', b'waqar', b'ahmed', b'ahmed'],
       [b'ahmed', b'ahmed', b'waqar', b'ahmed'],
       [b'ahmed', b'ahmed', b'ahmed', b'waqar']], dtype=object)>

#squaring, log, sqroot

In [118]:
I = tf.range(1,10)

In [117]:
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [120]:
tf.sqrt(tf.cast(I, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [123]:
tf.math.log(tf.cast(I, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#converting between numpy and tensors

In [124]:
J = tf.constant(np.array([1,2,3,4]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [126]:
np.array(J) #converting tensor to numpy

array([1, 2, 3, 4])